"""
Django settings for cal_proj project.

Generated by 'django-admin startproject' using Django 3.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path, os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'o8_a@%0t#a+w^vf+2y5@1ap6$_ly*m!u0v#(jl6&gj03w0=-i2'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
'13.233.55.113',
'engcalc.in',
'www.engcalc.in',
'localhost',
'127.0.0.1',]


# Application definition

INSTALLED_APPS = [
    'add_app.apps.AddAppConfig',
    'sub_app.apps.SubAppConfig',
    'user_app.apps.UserAppConfig',
    'rd_torque_app.apps.RdTorqueAppConfig',
    'ecc_drive_app.apps.EccDriveAppConfig',
    'servo_345cv_app.apps.Servo345CvAppConfig',
    'servo345_app.apps.Servo345AppConfig',
    'flywheel_app.apps.FlywheelAppConfig',
    'link_drive_app.apps.LinkDriveAppConfig',
    'block_weight_app.apps.BlockWeightAppConfig',
    'rw_weight_app.apps.RwWeightAppConfig',
    'rw_inertia_app.apps.RwInertiaAppConfig',
    'rw_gear_app.apps.RwGearAppConfig',
    'rw_presstorque_app.apps.RwPresstorqueAppConfig',
    'rw_pressspeed_app.apps.RwPressspeedAppConfig',
    'rw_thread_app.apps.RwThreadAppConfig',
    'rw_powerscrew_app.apps.RwPowerscrewAppConfig',
    'rw_shaftstr_app.apps.RwShaftstrAppConfig',
    'rw_ld_app.apps.RwLdAppConfig',
    'rw_bush_app.apps.RwBushAppConfig',
    'rw_bed_app.apps.RwBedAppConfig',
    'rw_crown_app.apps.RwCrownAppConfig',
    'rw_slide_app.apps.RwSlideAppConfig',
    'rw_key_app.apps.RwKeyAppConfig',
    'rw_sphcontact_app.apps.RwSphcontactAppConfig',
    'rw_cylcontact_app.apps.RwCylcontactAppConfig',
    'rw_gearstrength_app.apps.RwGearstrengthAppConfig',
    'draglink_app.apps.DraglinkAppConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'crispy_forms',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'cal_proj.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'cal_proj.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'user_app/templates')
]
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATIC_URL = '/static/'
LOGIN_REDIRECT_URL = 'home-users'
CRISPY_TEMPLATE_PACK = 'bootstrap4'
