# Generated by Django 3.1.7 on 2021-03-23 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmallServoMotor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=20)),
                ('motor_model', models.CharField(max_length=50)),
                ('rated_torque', models.FloatField()),
                ('torque_at_0_rpm', models.FloatField()),
                ('max_torque', models.FloatField()),
                ('torque_at_max_rpm', models.FloatField()),
                ('rated_rpm', models.FloatField()),
                ('max_rpm', models.FloatField()),
                ('rpm_at_max_torque', models.FloatField()),
                ('rated_power', models.FloatField()),
                ('inertia_with_brake', models.FloatField()),
                ('inertia_without_brake', models.FloatField()),
                ('weight_with_brake', models.FloatField()),
                ('weight_without_brake', models.FloatField()),
            ],
        ),
    ]
