# Generated by Django 3.1.7 on 2021-03-23 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servo345_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smallservomotor',
            name='motor_series',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smallservomotor',
            name='shaft_height',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='smallservomotor',
            name='max_rpm',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='smallservomotor',
            name='rated_rpm',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='smallservomotor',
            name='rpm_at_max_torque',
            field=models.IntegerField(),
        ),
    ]
